version: '3.5'
services:

  flask:
    build:
      context: ./flask  # Required, the folder we want to launch the command from if we did it using docker
      dockerfile: ./flask.Dockerfile
      labels:
      - "RES=HTTP"
    image: res-flask-app
    ports:
      - "8301:5000"
    networks:
      default:
    labels:
    - "RES=HTTP"

  express:
    build:
      context: ./express  # Required, the folder we want to launch the command from if we did it using docker
      dockerfile: ./express.Dockerfile
      labels:
      - "RES=HTTP"
    image: res-express-app
    ports:
      - "8302:8080"
    networks:
      default:
        aliases:
        - students-api

    labels:
    - "RES=HTTP"

  crow:
    build:
      context: ./cpp  # Required, the folder we want to launch the command from if we did it using docker
      dockerfile: ./Dockerfile
      labels:
      - "RES=HTTP"
    image: res-crow-app
    ports:
      - "8303:18080"
    networks:
      default:
    labels:
    - "RES=HTTP"
